name: 'Create Azure Container Registry'

on:
  workflow_dispatch:
    inputs:
      select-environment:
        required: true
        description: 'Select the environment to deploy the infrastructure'
        default: 'Beezly'
        type: choice
        options:
        - infra
        - infra-uat
        - infra-demo

permissions:
  contents: read 

jobs:
  terraform:        
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: artifacts/acr
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set TF_VARS_FILE_Name based on environment
      run: |
        if [[ "${{ github.event.inputs['select-environment'] }}" == "infra" ]]; then
          echo "TF_VARS_FILE_Name=terraform.tfvars" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs['select-environment'] }}" == "infra-uat" ]]; then
          echo "TF_VARS_FILE_Name=uat-terraform.tfvars" >> $GITHUB_ENV
        elif [[ "${{ github.event.inputs['select-environment'] }}" == "infra-demo" ]]; then
          echo "TF_VARS_FILE_Name=demo-terraform.tfvars" >> $GITHUB_ENV
        fi

    - name: Terraform Plan
      run: terraform plan -var-file=${{ env.TF_VARS_FILE_Name }}
