name: 'Create Azure Container Registry'

on:
  workflow_dispatch:
    inputs:
      select-environment:
        required: true
        description: 'Select the environment to deploy the infrastructure'
        default: 'Beezly'
        type: choice
        options:
        - beezly
        - beezly-uat
        - beezly-demo

permissions:
  contents: read 
      

jobs:
  terraform:        
    name: 'Terraform'
    env:
      ENVIRONMENT: ${{ github.event.inputs.select-environment }}
      STATE_FILE: ${{ github.event.inputs.select-environment }}.tfstate
      TF_VARS_FILE_Name: ''
      run: |      
        if [[ "${{ github.event.inputs.select-environment }}" == "beezly" ]]:        
            env:  TF_VARS_FILE_Name="terraform.tfvars"
        elif [[ "${{ github.event.inputs.select-environment }}" == "beezly-uat" ]]:
            env: TF_VARS_FILE_Name="uat-terraform.tfvars"
        elif [[ "${{ github.event.inputs.select-environment }}" == "beezly-demo" ]]:
            env: TF_VARS_FILE_Name="demo-terraform.tfvars"
        echo "TF_VARS_FILE_Name=$TF_VARS_FILE_Name"
        echo "ENVIRONMENT=$ENVIRONMENT"
        echo "STATE_FILE=$STATE_FILE"
        echo "ARM_CLIENT_ID=$ARM_CLIENT_ID"

    runs-on: ubuntu-latest        
    
    defaults:
      run:
        working-directory: artifacts/acr
        shell: bash
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Terraform Init
      run: terrafom plan -var-file=${{ env.TF_VARS_FILE_Name }}
